---
title: "project"
author: "Maya Zhao"
date: '2022-05-06'
output: html_document
---


Attribute Information:

Date Time: Each ten minutes.
Temperature: Weather Temperature of Tetouan city.
Humidity: Weather Humidity of Tetouan city.
Wind Speed of Tetouan city.
general diffuse flows
diffuse flows
power consumption of zone 1 of Tetouan city.
power consumption of zone 2 of Tetouan city.
power consumption of zone 3 of Tetouan city.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls()) #initialization
library(tidyverse)
library(data.table)
library(lubridate)
library(dplyr)
library(lubridate)
library(forecast)
library(janitor)
library(snakecase)
```

```{r}
# read the real data on July 1 for test
df <- readr::read_csv("Tetuan City power consumption.csv")
colnames(df)
```
```{r}
#clean_names(df,case="snake")
#colnames(df)
```




```{r}
# check for missing values
sum(is.na(df))
```


```{r}
# ts plot and acf plot
var = colnames(df)
var = var[-1]
for(i in var) {       
  ts.plot(df[[i]], ylab=i)
  acf(df[[i]], ylab = paste0(i," ACF"), main="")
}
```



```{r}
library(tseries)
for(i in var) {       
  print(adf.test(df[[i]])) # detects stationarity
  print(kpss.test(df[[i]],null = "Trend")) # detects trend stationarity
}
```

```{r}
fit_week = auto.arima(ts(df$`Zone 1 Power Consumption`,frequency = 6*24*52.18), seasonal = T)
fit_week
```


```{r}
fit_annual = auto.arima(ts(df$`Zone 1 Power Consumption`,frequency = 6*24*365.25), seasonal = T)
fit_annual
```

```{r}
colnames(df)[7] <- "Zone1"
colnames(df)[8] <- "Zone2"
colnames(df)[9] <- "Zone3"
```


```{r}
df$DateTime <-as.POSIXct(df$DateTime, format="%m/%d/%Y %H:%M")
#attr(df$DateTime, "tzone") <- "Africa/Casablanca"

df$year <- year(df$DateTime)
df$month <- month(df$DateTime)
df$week <- week(df$DateTime)
df$day <- day(df$DateTime)
df$hour <- hour(df$DateTime)
df$minute <- minute(df$DateTime)
```



```{r}
df_weekly <- filter(df,week == 1)
Z1_weekly <- ts(df_weekly$Zone1, frequency=6*24*52, start=c(2017,1))
plot(Z1_weekly, xlab = "Time", ylab = "Watt Hours", main = "Zone 1 Power Consumption")
```

```{r}
Z2_weekly <- ts(df_weekly$Zone2, frequency=6*24*52, start=c(2017,1))
plot(Z2_weekly, xlab = "Time", ylab = "Watt Hours", main = "Zone 2 Power Consumption")
```

```{r}
Z3_weekly <- ts(df_weekly$Zone3, frequency=6*24*52, start=c(2017,1))
plot(Z3_weekly, xlab = "Time", ylab = "Watt Hours", main = "Zone 3 Power Consumption")
```
```{r}
df_weekly_hm <- filter(df, hour == 20 & minute == 0)
Z1_weekly_hm <- ts(df_weekly_hm$Zone1, frequency=52)
comp_Z1 <- decompose(Z1_weekly_hm)
plot(comp_Z1)
```
```{r}
lm1 <- tslm(Z1_weekly_hm ~ trend + season)
summary(lm1)
```


