---
title: "tbats_model"
author: "Kartik Garg"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning=FALSE, message=FALSE}
library(TSA, warn.conflicts = FALSE)
library(forecast)
library(Metrics)
library(xts)
library(gdata)
library(readxl)
library(tseries)
library(dplyr)
```

## TBATS Model on Tetuan City power consumption

```{r}
df <- read.csv("Tetuan City power consumption.csv")
head(df)
```

Splitting into train and test

```{r}
df$DateTime <- as.POSIXct(df$DateTime,format="%m/%d/%Y %H:%M")
df2<-df[df$DateTime >= "2017-01-01" & df$DateTime < "2017-12-01",]
df2<-df2[complete.cases(df2), ]
history <- data.frame(ds = df2$DateTime, y = df2$Zone.1.Power.Consumption)
tail(history)
```

```{r}
test <- df[df$DateTime >= "2017-12-01",]
test<-test[complete.cases(test), ]
```

## TBATS with varying seasonality

### Daily

```{r}
m1 <- tbats(ts(history$y, frequency = 144), seasonal.periods = 144)
comp <-tbats.components(m1)
plot(comp)
```

```{r}
tbats_preds <- forecast(m1, h=nrow(test))
plot(tbats_preds)
```

```{r}
tbats_preds <- data.frame(tbats_preds)
pred_df <- data.frame(hours=test$DateTime, test_val=test$Zone.1.Power.Consumption, pred_val=tbats_preds$Point.Forecast)
d<- melt(pred_df, id.vars = "hours")

ggplot(d, aes(x=hours, y=value, color=variable)) + 
  geom_point(size=1) + 
  geom_line()
```

```{r}
smape(test$Zone.1.Power.Consumption,tbats_preds$Point.Forecast) 
```

### Weekly

```{r}
m1 <- tbats(ts(history$y, frequency = 144*7), seasonal.periods = 144*7)
comp <-tbats.components(m1)
plot(comp)
```

```{r}
tbats_preds <- forecast(m1, h=nrow(test))

plot(tbats_preds)
```

```{r}
tbats_preds <- data.frame(tbats_preds)
pred_df <- data.frame(hours=test$DateTime, test_val=test$Zone.1.Power.Consumption, pred_val=tbats_preds$Point.Forecast)
d<- melt(pred_df, id.vars = "hours")

ggplot(d, aes(x=hours, y=value, color=variable)) + 
  geom_point(size=1) + 
  geom_line()
```

```{r}

smape(test$Zone.1.Power.Consumption,tbats_preds$Point.Forecast) 
```

### Yearly

```{r}
m1 <- tbats(ts(history$y, frequency = 144*365), seasonal.periods = 144*365)
comp <-tbats.components(m1)
plot(comp)
```

```{r}
tbats_preds <- forecast(m1, h=nrow(test))

plot(tbats_preds)
```

```{r}
tbats_preds <- data.frame(tbats_preds)
pred_df <- data.frame(hours=test$DateTime, test_val=test$Zone.1.Power.Consumption, pred_val=tbats_preds$Point.Forecast)
d<- melt(pred_df, id.vars = "hours")

ggplot(d, aes(x=hours, y=value, color=variable)) + 
  geom_point(size=1) + 
  geom_line()
```

```{r}
smape(test$Zone.1.Power.Consumption,tbats_preds$Point.Forecast) 
```
